### ISSUE TITLE
Is this repo maintained?

### ISSUE THREAD

**Issue by yusufcanb** [underlines/awesome-ml#25]

**Comment by adRn-s** [comment]
Yes

**Comment by yusufcanb** [comment]
Thank you. What is the average response time for Pull Requests?

**Comment by adRn-s** [comment]
I saw one merged 5 days ago, hence my answer.

**Comment by underlines** [comment]
Please see my comment on your PR:

https://github.com/underlines/awesome-ml/pull/24

**Comment by yusufcanb** [comment]
Updated, thanks for the feedback.
